fail_fast: true
repos:
  - repo: https://github.com/python-poetry/poetry
    rev: 1.3.2
    hooks:
      # Check poetry configuration
      - id: poetry-check

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.4
    hooks:
      # Format javascript, json, yaml, ...
      - id: prettier

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-black
          - black==23.1.0 # must conform to pyproject.toml

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.33.0
    hooks:
      - id: markdownlint-fix
        args:
          - --disable
          - MD013 # line-length
          - --

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # Avoid committing large files
      - id: check-added-large-files
      # Add newline to end of file if missing
      - id: end-of-file-fixer
      # Change Windows end of line by linux end of line
      - id: mixed-line-ending
        args: ["--fix=lf"]
      # Remove trailing whitespace
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: ruff
        name: ruff
        description: Run 'ruff' for extremely fast Python linting
        entry: poetry run ruff --force-exclude
        args: [--force-exclude, --fix, --exit-non-zero-on-fix]
        language: system
        types_or: [python, pyi]
        require_serial: true
      - id: black
        name: black
        description: "Black: The uncompromising Python code formatter"
        entry: poetry run black
        language: system
        types_or: [python, pyi]
        require_serial: true
      - id: pytest
        name: pytest
        entry: poetry run pytest
        language: system
        pass_filenames: false
        always_run: true
      - id: pyright
        name: pyright
        description: Python command line wrapper for pyright, a static type checker
        entry: poetry run pyright
        language: system
        types_or: [python, pyi]
        require_serial: true
