[tool.poetry]
name = "python project template"
version = "0.1.0"
description = ""
authors = ["Thomas PERRIN <thomas.perrin@drotek.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.8.2"
numpy = "^1.23.4"
pydantic = "^1.10.2"


[tool.poetry.group.dev.dependencies]
pre-commit = "^2.20.0"
black = {version = "^22.10.0", allow-prereleases = true}
flake8 = "^5.0.4"
pytest = "^7.2.0"
mypy = "^0.990"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
target-version = ['py38']

[tool.isort]
profile = "black"
