name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Load cached Poetry installation
        id: cached-poetry
        uses: actions/cache@v3
        with:
          path: ~/.local
          key: ${{ runner.os }}-poetry-0 # Increment this to invalidate the cache
      - name: Install poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Load cached venv
        uses: actions/cache@v3
        with:
          path: .venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
      - name: Load cached pre-commit
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-pre-commit-${{ hashFiles('**/.pre-commit-config.yaml') }}
      - name: Install dependencies
        run: poetry install
      - name: Run Ruff Linter # Run Ruff Linter separately for better integration with GitHub
        run: poetry run ruff check --output-format=github .
      - name: Run pre-commit
        run: poetry run pre-commit run --all-files --show-diff-on-failure
        env:
          SKIP: ruff-check
